### ISSUE TITLE
Add Prometheus alerts for MongoDB

### ISSUE THREAD

**Issue by samber** [samber/awesome-prometheus-alerts#1]

**Comment by Slach** [comment]
https://github.com/percona/mongodb_exporter maybe this?

**Comment by samber** [comment]
Hi @Slach 

We already inserted some rules for dcu/mongodb_exporter

But I would be happy to add new alerting rules if you copy-paste here, some alert that fit with percona/mongodb_exporter.

**Comment by Zhang21** [comment]
> https://github.com/percona/mongodb_exporter maybe this?

same requests.
