### ISSUE TITLE
Kubernetes Pod not healthy is not working correcly

### ISSUE THREAD

**Issue by Seljuke** [samber/awesome-prometheus-alerts#100]
Hello,

Alert query for Kubernetes Pod healt need to be fixed. Kube state metric assigns the value of current  pod phase with 1.

https://github.com/samber/awesome-prometheus-alerts/blob/c20227b458f521c5b3b4cfb2c71d5a93428ef540/_data/rules.yml#L989

Correct expression:

```
min_over_time(sum by (namespace, pod) (kube_pod_status_phase{phase=~"Pending|Unknown|Failed"} == 1)[1h:])
```

**Comment by samber** [comment]
![](https://media.giphy.com/media/WnvzaaOHRTKPS/giphy.gif)

Thanks for the report ;)

Let's merge.

**Comment by iJebus** [comment]
The version live at https://awesome-prometheus-alerts.grep.to/rules#rule-kubernetes-16 hasn't been updated, does that mean all the other rules there may be out of date or..?
