### ISSUE TITLE
Change in network average transmit

### ISSUE THREAD

**Issue by therist** [samber/awesome-prometheus-alerts#102]
This is a good way to be notified in case of intrusion, DDOS attack or just a dumb user doing something stupid with a server. 

If average traffic increases a lot over the last 5 min. compared to the last 5h, you get an alert. 

(sum by (instance) (avg_over_time(node_network_transmit_bytes_total[5m])))/(sum by (instance) (avg_over_time(node_network_transmit_bytes_total[5h])))

(sum by (instance) (avg_over_time(node_network_receive_bytes_total[5m])))/(sum by (instance) (avg_over_time(node_network_receive_bytes_total[5h])))

**Comment by samber** [comment]
I'm not sure these rules are suitable here.

Most applications have varying load over the day/week. Such alert would be firing very often.

Tracking the max expected bandwidth for your server is probably more accurate.
