### ISSUE TITLE
rabbitmq rules don't work

### ISSUE THREAD

**Issue by xakaitetoia** [samber/awesome-prometheus-alerts#103]
Hello,
Do you maybe have updated rabbitmq rules as these are not working (most of them)?
The metrics you have specified in the expressions do not exist so i have made similar (kinda). Any feedback appreciated and thanks.

**Comment by samber** [comment]
Hi @xakaitetoia and thanks for the report.

These rules are based on the following exporter: https://github.com/kbudde/rabbitmq_exporter

Which one do you use ?

**Comment by xakaitetoia** [comment]
Hello,
I am using the official one and latest rabbitmq version
https://github.com/rabbitmq/rabbitmq-prometheus
I believe everyone is using this in their production. 
I couldn't find the below alerts/metrics:
 - alert: RabbitmqClusterDown
    expr: sum(rabbitmq_running) < 3
  - alert: RabbitmqClusterPartition
    expr: rabbitmq_partitions > 0
I have found another way for checking the cluster numbers (with identity_info) but for partitions i haven't found anything similar.

**Comment by paulfantom** [comment]
All metrics from official exporter are in https://github.com/rabbitmq/rabbitmq-prometheus/blob/master/src/collectors/prometheus_rabbitmq_core_metrics_collector.erl. There is nothing to check directly if cluster is partitioned. You probably will need to play aroung with `rabbitmq_node` and `rabbitmq_cluster` from `identity_info` metric.

**Comment by xakaitetoia** [comment]
yeap i already did that @paulfantom  ;) thanks.

**Comment by Slach** [comment]
@xakaitetoia feel free to share your rules for official exporter as a pull request
