### ISSUE TITLE
Postgresql replication lag alert syntax error

### ISSUE THREAD

**Issue by Yitaek** [samber/awesome-prometheus-alerts#104]
This alert (https://github.com/samber/awesome-prometheus-alerts/blob/951d80121f612845f82c0d1a6ec66527a87d384f/_data/rules.yml#L365) has a syntax error (missing right parentheses):

query should be (parentheses bolded below) 

(pg_replication_lag > 10 **)** and ON(instance) (pg_replication_is_replica == 1)

**Comment by samber** [comment]
Oops.

Thanks for the report. I just fixed on master branch.

![](https://media.giphy.com/media/HyCxJErg9jTCU/giphy.gif)
