### ISSUE TITLE
Consensus on severity label

### ISSUE THREAD

**Issue by robert-will-brown** [samber/awesome-prometheus-alerts#109]
Is there any standard or agreed meaning on the severity levels?

I can't see anywhere that documents it - apologies if it exist.

**Comment by paulfantom** [comment]
> Is there any standard or agreed meaning on the severity levels?

Overall in prometheus community de-facto there are 3 levels used:
- critical (page and wake up human operator)
- warning (something is wrong, but can wait)
- info

The first two are commonly used, the third one is rarely seen.

---
As for this repo - I don't think there is anything said.

**Comment by Turgon37** [comment]
@robert-will-brown Hello, I recommend you to set alerting severities according to your final notification backend or to your team's workflow.
For example, Alerta which aim to be an aggregator of multiple alerting and monitoring backends define initially the following set of severity levels
https://docs.alerta.io/en/latest/api/alert.html#alert-severities

Zabbix introduce this subset https://www.zabbix.com/documentation/2.0/manual/config/triggers/severity that is really extended than the one Nagios initially offered.

**Comment by paulfantom** [comment]
Sorry for pinging everyone on this already closed issue. This information is mostly for people who find this issue in the future.

---
I was just reading what [ITIL](https://en.wikipedia.org/wiki/ITIL) has to say about it and now I get why prometheus community use only info/warning/critical type of alerts.

> Standard categorization based on the significance of an event:
>
> Informational (INFO): the event does not require any immediate action and does not represent an exception. They are recorded in the log files and maintained for a predetermined period. This type of event is used to check the status of a device or service, to confirm the state of an activity, to generate statistics (user login, batch job completed, device power up, number of users logged into an application)
> Warning (WARN / ALERT): the event is generated when a device or service, (application / utility), is approaching an agreed threshold (KPI). Warnings are intended to notify the group/process/tool in order to take the necessary actions to prevent an exception occurring.
> Exception (ERROR): means that a service or device is currently operating below the normal parameters/indicators (predefined). This mean that the business service is impacted and the device or service presents a failure, performance degradations or loss of functionality (web server down, CS coverage lost for several sites). A device failure is an error.”

**Comment by samber** [comment]
As far as I remember, I have never written an alert with `ìnfo` severity. 
Did you do that already ? Can you give an example ?

It can be useful for postmortem analysis, but Grafana or ELK would be more convenient for this job...

**Comment by paulfantom** [comment]
`info` is very rarely used (for example in OpenShift we are shipping only one such alert: https://github.com/openshift/cluster-monitoring-operator/blob/master/assets/prometheus-k8s/rules.yaml#L911-L920). Usually those are meant to allow testing expressions in "real-world" situations with the aim to later graduate alert to `warning` or `critical` type. Which means those are more meaningful for application developers that end-users.

And as you said, grafana or logging is usually better suited for postmortem analysis.
