### ISSUE TITLE
Should cadvisor metrics filter out metrics with no name?

### ISSUE THREAD

**Issue by prontog** [samber/awesome-prometheus-alerts#113]
Hello and thanks for this great list of alerts!

I've been using them for a while on my raspberry pi cluster and have noticed that, although I pass `--docker_only=true`, for each metric there is one with no name label (I don't know what it stands for) which can trigger alerts quite often. I name all my containers and when I filter with `{name != "" }` I just get the metrics for the containers and no false alarms.

Should the *cadvisor* alerts filter out these metrics with no name label or am I missing something here? What do the signify? Especially since I run the cadvisor with  `--docker_only=true`?

Best regards

Panos

**Comment by samber** [comment]
I added a comment => #151
