### ISSUE TITLE
Translate rules from node_exporter to Netdata metrics

### ISSUE THREAD

**Issue by mbarper** [samber/awesome-prometheus-alerts#122]
Do you think it is interesting to translate all those rules from node_exporter to Netdata metrics so you can use a different source for the metrics?

I particularly use Netdata metrics as a source for Prometheus, so I will translate for me those rules I consider interesting. I can share if you think that could be useful.

**Comment by samber** [comment]
Hi @mbarper 

Sure, I just discovered Netdata have a Prometheus exporter. Good news!

If you wrote some rules, feel free to open a PR.
Or share it in this issue and I will find time to create a PR.

**Comment by samber** [comment]
Many rules have been added.

Closing.
