### ISSUE TITLE
Send alert that everyting if fine

### ISSUE THREAD

**Issue by optimistic5** [samber/awesome-prometheus-alerts#124]
I would like to receive alert (notification) every week/month to understand that alert system is working.

One of the thoughts is to use Unix time `node_time_seconds` and create some pattern for every week or month. I found this [post](https://stackoverflow.com/a/38000383), but didn't manage to use the formula.

**How can send alerts that everything is fine?**

**Comment by optimistic5** [comment]
I found out the workaround.
It is possible to send  alert using curl, so this is works for me
```bash
docker run -it --rm --name dummy-alert --network nginx-proxy curlimages/curl sh -c "curl -H \"Content-Type: application/json\" -d '[{\"labels\":{\"alertname\":\"TestAlert1critical\", \"severity\":\"critical\"}}]' http://alertmanager:9093/api/v1/alerts"
```
But problem that I receive few **Firing** and after some time **Resolved**.
![image](https://user-images.githubusercontent.com/25054050/83187238-892daf80-a136-11ea-90a1-4e4fc807a97e.png)


I tried to send Resolved curl, 
```bash
docker run -it --rm --name dummy-alert --network nginx-proxy curlimages/curl sh -c "curl -H \"Content-Type: application/json\" -d '[{\"status\": \"resolved\",\"labels\":{\"alertname\":\"TestAlert1resolvedinfo\", \"severity\":\"info\"}}]' http://alertmanager:9093/api/v1/alerts"
```
but works the same. 

**Is the any way to receive only notification, without firing and resolved?**

**Comment by paulfantom** [comment]
Please see discussion in https://github.com/samber/awesome-prometheus-alerts/pull/106 to see why this is an anti-pattern.

---

> create some pattern for every week or month

Use [holiday_exporter](https://github.com/allangood/holiday_exporter)

**Comment by optimistic5** [comment]
@paulfantom thank you for your answer. I will take a look on it.
