### ISSUE TITLE
Add Prometheus alerts for Etcd

### ISSUE THREAD

**Issue by samber** [samber/awesome-prometheus-alerts#13]

**Comment by opskumu** [comment]
etcd alerts can reference: https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml  ：）

**Comment by samber** [comment]
@opskumu definitely !

I'll prepare a PR.

**Comment by opskumu** [comment]
@samber etcd alerts has been moved to https://github.com/helm/charts/tree/master/stable/prometheus-operator/templates/prometheus/rules 

> https://github.com/coreos/prometheus-operator/tree/master/helm
