### ISSUE TITLE
Error: found character that cannot start any token

### ISSUE THREAD

**Issue by kovaxur** [samber/awesome-prometheus-alerts#132]
Hi,
I have some issues with the parsing of the alert rules, for example:

HostEdacUncorrectableErrorsDetected

**Test yaml file:**
groups:
- name: "test"
  rules:
  - alert: HostEdacUncorrectableErrorsDetected
    expr: node_edac_uncorrectable_errors_total > 0
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host EDAC Uncorrectable Errors detected (instance {{ $labels.instance }})"
      description: "{{ $labels.instance }} has had {{ printf "%.0f" $value }} uncorrectable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

**Error message from promtool:**
/etc/prometheus/alerts/test.yml: yaml: line 11: found character that cannot start any token

**Promtool version:**
promtool, version 2.19.1 (branch: HEAD, revision: eba3fdcbf0d378b66600281903e3aab515732b39)
  build user:       root@62700b3d0ef9
  build date:       20200618-16:35:26
  go version:       go1.14.4

**Yaml validator says:**

Error : Unexpected characters near "%.0f" $value }} uncorrectable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"".
Line : 11  description: "{{ $labels.instance }} has had {{ printf "%.0f" $value }} uncorrectable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

When I change the leading " to ' for description, everything is fine. I have the same problem with some other alert rules. What am I doing wrong?

Thanks

**Comment by Shirakiina** [comment]
Please use    \"%.0f\"     instead of    "%.0f"

**Comment by samber** [comment]
Thanks @Shirakiina for helping.

You need to scape the `"` when your yaml string starts with `"`.

In that case, just embed your string into a `'`, instead of adding a backslash ;)
