### ISSUE TITLE
Slack template for customizable alerts

### ISSUE THREAD

**Issue by shubhamc183** [samber/awesome-prometheus-alerts#142]
A customizable slack template which can show
- alert name
- alert description
- labels
- Firing/Resolved in message
- color on the basis of severity
- Links to the source(Prometheus) and the silence.

![image](https://user-images.githubusercontent.com/15362871/90973818-32702000-e543-11ea-80ed-559e5305b321.png)

A slack template: `slack.tmpl` which can be referenced via alertmanager.yml like

```
templates:
  - slack.tmpl
```

I want to send a PR.

**Comment by samber** [comment]
An alert template is already suggested on the following page => https://awesome-prometheus-alerts.grep.to/alertmanager

Feel free to improve it, and open a PR ;)
