### ISSUE TITLE
Adding alerting rule - top-like CPU iowait (and others) percentage

### ISSUE THREAD

**Issue by gitqlt** [samber/awesome-prometheus-alerts#153]
According to the hints:
How to display IOwait percentage in Prometheus, Prometheus: Lighting The Way
- https://velenux.wordpress.com/2017/05/05/how-to-display-iowait-percentage-in-prometheus/
and
- https://movio.co/blog/prometheus-lighting-the-way/

I suggest to use their rule:
```
avg by (instance) (irate(node_cpu_seconds_total{mode="iowait"}[1m])) * 100
```
See above compared to Zabbix, system.cpu.util[,iowait]
![iowait_percentage_1h_Zabbix+Prom](https://user-images.githubusercontent.com/36642440/96321707-aea05480-1016-11eb-9936-a018a9ed92d3.png)

**Comment by samber** [comment]
Just added.

Thanks for the suggestion.

Note that `rate()` should be preferred to `irate()` for alerting.
