### ISSUE TITLE
PrometheusJobMissing misunderstanding

### ISSUE THREAD

**Issue by x20mar** [samber/awesome-prometheus-alerts#165]
Hey,

I just want to check that I don't have a misunderstanding on `PrometheusJobMissing`.

In the expression where it says `absent(up{job="prometheus"})` are you meant to replace `prometheus` with the name of the job you expect to be there? 

So for example, if you are using the Postgres Exporter, then you should change the expression to be `absent(up{job="metrics/prometheus-postgres-exporter/0"})`

Thanks

**Comment by samber** [comment]
`metrics/prometheus-postgres-exporter/0` seems to be an unusual job name.

To list available jobs, just execute the `up` query ;)

I'm closing this issue. Feel free to open it again!
