### ISSUE TITLE
Can't find queries.yml for postgresql_exporter

### ISSUE THREAD

**Issue by dusatvoj** [samber/awesome-prometheus-alerts#167]
Hi,
In postgresql rules (and maybe in some other too) are custom metrics. If I'm not blind I can't find files like `queries.yml` for exporters. Is it possible to add them to repo (or to some another repo, etc.)?
I didn't knew even that rules are not generic but custom.
Thank you.

**Comment by samber** [comment]
This repository provides alerts rules. It is not responsible for collecting metrics.

Look at this Prometheus architecture:

![image](https://user-images.githubusercontent.com/2951285/102776264-ba99f100-438e-11eb-8e1c-e0ccd238a521.png)

The `queries.yml` file you're talking about from [wrouesnel/postgres_exporter](https://github.com/wrouesnel/postgres_exporter) is at exporter level.

The goal of this repository is to show some generic alerts. Those checks are run on a regular basis by Prometheus. In case of alert (or alert termination), an event is pushed to alertmanager.

The `queries.yml` file is nice for collecting some business metrics about your app, such as the number of users, posts/comments in a blog...

If you need some examples, you should check the following file => https://github.com/wrouesnel/postgres_exporter/blob/master/queries.yaml

Closing this issue. Feel free to open it again.
