### ISSUE TITLE
api server latency triggering

### ISSUE THREAD

**Issue by mike-england** [samber/awesome-prometheus-alerts#181]
I've been getting a continual alarm for high api server latency from this rule:

`expr: histogram_quantile(0.9, sum(apiserver_request_latencies_bucket{verb!~"CONNECT|WATCHLIST|WATCH|PROXY"}) WITHOUT (instance, resource)) / 1e+06 > 1`

I was able to find an issue in the prometheus github repository: https://github.com/prometheus-operator/prometheus-operator/issues/751

That indicates the buckets are cumulative, so once it triggers it'd stay until the data rolls out of retention.

Based on what's there now, I'd suggest something like this:

`histogram_quantile(0.99, sum(rate(apiserver_request_latencies_bucket{subresource!="log",verb!~"^(?:CONNECT|WATCHLIST|WATCH|PROXY)$"} [10m])) WITHOUT (instance, resource)) / 1e+06 > 1`

When I put that into my prometheus instance it produces a nice graph for all of the different verbs which seems to make sense.  Maybe someone could have a look to confirm?

**Comment by samber** [comment]
ok, LGTM.

I'm going to commit this updated query.
Thanks for your help ;)
