### ISSUE TITLE
yaml errors for colons in yaml values

### ISSUE THREAD

**Issue by astiphout** [samber/awesome-prometheus-alerts#186]
This errors:

      description: Instance {{ $labels.instance }} has had {{ printf "%.0f" $value }} correctable memory errors reported by EDAC in the last 5 minutes.\n  VALUE= {{ $value }}\n  LABELS: {{ $labels }}

This is fine:
      description: Instance {{ $labels.instance }} has had {{ printf "%.0f" $value }} correctable memory errors reported by EDAC in the last 5 minutes.\n  VALUE= {{ $value }}\n  LABELS {{ $labels }}

**Comment by samber** [comment]
Closing as duplicate.
