### ISSUE TITLE
Linkable alerts and headers in https://awesome-prometheus-alerts.grep.to/rules.html

### ISSUE THREAD

**Issue by perlun** [samber/awesome-prometheus-alerts#188]
Hi,

It would be awesome if both the alerts and also the sections (like 1. 2. Host and hardware : node-exporter (31 rules) [copy section]) were clickable in-page links. That way, you could copy-paste a link to a particular part of this list which is useful when discussing a particular alert on e.g. Slack or elsewhere.

Thanks for a great collection all-in-all. :bowing_man:

**Comment by samber** [comment]
Hi @perlun and thanks for your suggestion!

I just added a small anchor on section and rule titles (displayed on hover):

![image](https://user-images.githubusercontent.com/2951285/105915875-81f5d300-6030-11eb-939b-24de3fbdfa2e.png)

**Comment by perlun** [comment]
Nice, thanks! Much better this way. :clap:
