### ISSUE TITLE
Execution Read and Write metric using mongodb-exporter for prometheus

### ISSUE THREAD

**Issue by som-kanade** [samber/awesome-prometheus-alerts#193]
I have below query for execution time for mongo using prometheus but that doesnot seem to give correct value 
can someone help here ?

```((avg(rate(mongodb_mongod_op_latencies_latency_total{type="write",mongo_cluster=~"$cluster_name"}[5m])) by (instance)) * on (instance) group_right mongodb_mongod_replset_my_name) * on (instance,name,service) group_right mongodb_mongod_replset_member_health{state=~"$type",set=~"$shardName",name=~"$instance"}```

**Comment by som-kanade** [comment]
@samber is there anything you can help here e?

**Comment by samber** [comment]
hi @som-kanade 

For urgent requests, I am available for freelancing.

I have no mongodb cluster on my side. Can you provide more information?

- the value you get
- dump of /metrics endpoint
- ...

**Comment by som-kanade** [comment]
@samber these are 2 metrics i am getting for above execution 
```
mongodb_mongod_op_latencies_latency_total{type="command"} 1.7620452432e+10
mongodb_mongod_op_latencies_latency_total{type="read"} 4.1813017058e+10
```

**Comment by som-kanade** [comment]
[metrics.txt](https://github.com/samber/awesome-prometheus-alerts/files/5921061/metrics.txt)
here is a dump

**Comment by samber** [comment]
I'm pretty sure you cannot get this value with this query.

Can you provide the value returned? As well as the expected result?

In your query, you are grouping by `service` label. But it does not appear in your `/metrics` dump. Can you confirm this label exists?

**Comment by som-kanade** [comment]
service is variable in Grafana btw

**Comment by samber** [comment]
There is no Grafana involved in Prometheus alerting.

Closing as this issue is going nowhere.
