### ISSUE TITLE
Hierarchically rules structure

### ISSUE THREAD

**Issue by gfrntz** [samber/awesome-prometheus-alerts#194]
Hello, 
It's just a suggestion for separating rule file to many files by groups. Cause after that someone can use raw files for automatization process.

For example:
Inside my automation tool i can add remote file with example url

```
https://raw.githubusercontent.com/samber/awesome-prometheus-alerts/master/rules/elasticsearch/NAME_OF_EXPORTER/rulefile.yaml
```

**Comment by varac** [comment]
I'd like this as well but unfortunatly, the rules file is not intended to be used like it is, but is beeing templated to the website:

># The following yaml cannot be copy-pasted to Prometheus configuration.
>#     Please navigate to https://awesome-prometheus-alerts.grep.to/rules instead.

It would be nice to have a converter which allows the rules to be translated easily to actual rules files.

**Comment by samber** [comment]
I think you should not automate alert creation.

But in case you need it anyway, just fetch one of the following files: https://github.com/samber/awesome-prometheus-alerts/blob/master/dist/rules/xxxx/yyyy.yml

Replace "xxxx" and "yyyy". See https://github.com/samber/awesome-prometheus-alerts/tree/master/dist/rules
