### ISSUE TITLE
yaml: line 20: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by loynoir** [samber/awesome-prometheus-alerts#199]
# Bug Description
[Website](https://awesome-prometheus-alerts.grep.to/rules) set wrong yaml data to clipboard.

# Bug reproduce
Copy paste rules from [website](https://awesome-prometheus-alerts.grep.to/rules) into prometheus-rules.yml.  Promtool-check report yaml error.
```sh
# promtool check rules prometheus-rules.yml 
Checking prometheus-rules.yml
  FAILED:
prometheus-rules.yml: yaml: line 20: mapping values are not allowed in this context
# sed -n 20p prometheus-rules.yml
      description: A Prometheus job has disappeared\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}
```

# Workaround
```sh
# sed -i 's/LABELS:/LABELS =/g' prometheus-rules.yml
# promtool check rules prometheus-rules.yml 
Checking prometheus-rules.yml
  SUCCESS: 25 rules found
```

# Possible Solution
This [pull](https://github.com/samber/awesome-prometheus-alerts/pull/182/files) seems can fix the bug.

**Comment by ngosang** [comment]
I having the same issue. The `:`after `LABEL` breaks the YAML format. Please use `=` instead of `:`.
As alternative you can quote the whole description, but I think it's better to replace the colon.

**Comment by samber** [comment]
I just merged the PR.
