### ISSUE TITLE
Some alerts fails validation

### ISSUE THREAD

**Issue by ngosang** [samber/awesome-prometheus-alerts#204]
In node-exporter, the following rules have malformed description because it starts with `{{`. You can add some text before or quote the whole description.
* HostEdacCorrectableErrorsDetected
* HostEdacUncorrectableErrorsDetected
* HostNetworkReceiveErrors
* HostNetworkTransmitErrors

```
Checking rules.yml
  FAILED:
     rules.yml: yaml: line 457: did not find expected key
     rules.yml: yaml: line 457: did not find expected key
```

**Comment by samber** [comment]
Thanks for the feedback. I published a new version with a better alert description.
