### ISSUE TITLE
Minor: new lines in copy section

### ISSUE THREAD

**Issue by ngosang** [samber/awesome-prometheus-alerts#205]
When I click `copy section` in `1. 2. Host and hardware : node-exporter ` the rules are right, but I get a lot of new lines between rules. This is not happening in all sections, I have found this issue in node-exporter and blackbox-exporter. Could be more.

https://awesome-prometheus-alerts.grep.to/rules#host-and-hardware

**Comment by samber** [comment]
Thanks for the report.

It was broken on every sections: 1 more `\n` at each click on "copy section".
