### ISSUE TITLE
mongotop — json equivalent metrics in prometheus using mongodb-exporter

### ISSUE THREAD

**Issue by som-kanade** [samber/awesome-prometheus-alerts#209]
I am running MongoDB-exporter and pushing data to Prometheus by default mongotop metric is disabled in MongoDB-exporter which I have enabled using --collect.topmetrics flag 
but enabling this flag is giving fewer metrics and I don't need those metrics 
when I run mongotop -- json on mongo node I am getting a couple of metrics that are pretty useful to me (read, write, total time and stuff per dB, collection, etc ..)
is there any flag in mongo-exporter that lets me get the get mongotop -- json equivalent metrics in Prometheus (https://github.com/percona/mongodb_exporter) this the exporter

**Comment by som-kanade** [comment]
@samber can you help here if possible ?

**Comment by samber** [comment]
Hi @som-kanade 

You better asking this in the mongodb_exporter repository.

If Mongotop metrics are not fully exported, it would be a good start for a contribution ;)

Closing.

**Comment by som-kanade** [comment]
Hey i dont think they are letting open issues on their repo 
looked for all flags didnot find any for mongotop metrics from percona exporter
https://github.com/percona/mongodb_exporter

**Comment by samber** [comment]
Looks like you have to go to Jira (see https://github.com/percona/mongodb_exporter/blob/main/CONTRIBUTING.md)

**Comment by som-kanade** [comment]
thanks
