### ISSUE TITLE
Website not workin

### ISSUE THREAD

**Issue by RohitAudit** [samber/awesome-prometheus-alerts#210]
![image](https://user-images.githubusercontent.com/79438614/113970483-9a664300-9854-11eb-99d3-1f19e924de55.png)

Website not working since 7th April evening .

**Comment by johannesboon** [comment]
DNS is broken for me as well, but as a workaround the info most people are interested in is still here on Github:

https://github.com/samber/awesome-prometheus-alerts/blob/master/_data/rules.yml

**Comment by simonszu** [comment]
Website is broken for me as well, but not for DNS but `ERR_SSL_PROTOCOL_ERROR`

**Comment by samber** [comment]
Oops, i forgot to renew the domain 😆 

It will come back to life shortly ;)

Thanks for your report guys! ❤️

**Comment by samber** [comment]
Ok, nameservers are propagated. :rocket:

I should use some blackbox rules for tracking this error. :trollface: 

![](https://media.giphy.com/media/NuWTbZ4mAx2EyH0eXt/giphy.gif)

**Comment by michaelmcmillan** [comment]
Did it happen again, @samber ? 😅

**Comment by samber** [comment]
yes, but the registrar's website is broken

I'm yelling at them for a few days

**Comment by michaelmcmillan** [comment]
Ah, as a temporary fix I found a nameserver in Bangladesh with a cached record of the IP address (`172.67.178.181`). I just pinned that to my `/etc/hosts` file. In case anyone else is in the same situation.

**Comment by samber** [comment]
This is a GitHub page actually ;)
