### ISSUE TITLE
Missing PostgreSQL metrics?

### ISSUE THREAD

**Issue by dimitrigraf** [samber/awesome-prometheus-alerts#219]
Hi

First of all: Thanks for this great collection of Prometheus alerts!

I have a quick question: What version of the PostgreSQL exporter do I need to run, to be able to use all the metrics found in your collection of PostgreSQL alarms?

I tried a lot of different versions, both from the [community repo](https://hub.docker.com/r/prometheuscommunity/postgres-exporter) and the one from [wrouesnel](https://hub.docker.com/r/wrouesnel/postgres_exporter), but there are some metrics that just don't show up. One such example is the `pg_slow_queries`. Another one is `pg_xlog_position_bytes`. 

Are some metrics only available with newer versions of Postgres? Could that be it? I am running Postgres 12.

Thanks in advance!

**Comment by samber** [comment]
I removed the associated rules.
