### ISSUE TITLE
add detection for swap space absence

### ISSUE THREAD

**Issue by astiphout** [samber/awesome-prometheus-alerts#222]
node_exporter:

 - alert: HostSwapIsAbsent
    expr: node_memory_SwapFree_bytes == 0
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Host swap is not Present (instance {{ $labels.instance }})
      description: "Swap is empty\n  VALUE = {{ $value }}\n  LABELS {{ $labels }}"

**Comment by paulfantom** [comment]
Why would you alert on something that is not changing during operations? Setting swap is a configuration choice and not something that can suddenly disappear.

**Comment by astiphout** [comment]
You are right, this is a deployment 'problem' but I'm just the user of the VM, therefor I added an alarm for it. Indeed it is a one-off so although useful for me, maybe not for anybody else.

**Comment by samber** [comment]
Closing, since we already have an alert for low swap.
