### ISSUE TITLE
add Container = Absent check

### ISSUE THREAD

**Issue by astiphout** [samber/awesome-prometheus-alerts#223]
We have already:
  - alert: ContainerKilled
    expr: time() - container_last_seen > 30
    for: 0m
    labels:
      severity: warning
    annotations:
      summary: Container killed (instance {{ $labels.instance }})
      description: "A container has disappeared\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

But once it does not return at all there is no alarm: this alarm is added to the previous one.

  - alert: ContainerAbsent
    expr: absent(container_last_seen)
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Container absent after 5min (instance {{ $labels.instance }})
      description: "A container has permanently disappeared\n  VALUE = {{ $value }}\n  LABELS {{ $labels }}"

See: https://github.com/google/cadvisor/issues/2305

**Comment by laurivosandi** [comment]
Additionally: For me the ContainerKilled alert is pretty useless, it trips every time I restart Docker services because the identifier label `id` changes. Same would happen with proposed ContainerAbsent as well.

**Comment by samber** [comment]
I just made a PR: #247

I added a comment to ensure those rules will be used carefully.

WDYT @laurivosandi @astiphout 

![image](https://user-images.githubusercontent.com/2951285/135773092-8fef26bc-711e-4e65-b800-c365aafa4e96.png)
