### ISSUE TITLE
some metrics  not exist in postgres exporter !!!

### ISSUE THREAD

**Issue by jwh5566** [samber/awesome-prometheus-alerts#225]
Hello!    thanks for the project, it is great!
 i have installed the newest postgres exporter from community  and the metrics is ok,but in the web http://xxxxx/metrics,  i could not find some metrics in prometheus-alerts like: 
pg_replication_lag 
pg_postmaster_start_time_seconds 
pg_stat_user_tables_last_autovacuum 

so  why these metrics  not exists，is the postgres exporter problem？？？
expecting a reply， Thanks for all

**Comment by samber** [comment]
Those metrics come from [queries.yaml](https://github.com/prometheus-community/postgres_exporter/blob/master/queries.yaml) file ;)

See README: https://github.com/prometheus-community/postgres_exporter#adding-new-metrics-via-a-config-file
