### ISSUE TITLE
Istio IstioHighRequestLatency rule triggered often

### ISSUE THREAD

**Issue by PeteMac88** [samber/awesome-prometheus-alerts#226]
Hey there,
I am having some problems understanding why the [`IstioHighRequestLatency`](https://awesome-prometheus-alerts.grep.to/rules.html#rule-istio-1-8) rule is triggered for my services while the monitoring is not showing any problems.

The expression for the rule is as followed:
```
rate(istio_request_duration_milliseconds_sum{reporter="destination"}[1m]) / rate(istio_request_duration_milliseconds_count{reporter="destination"}[1m]) > 0.1
```
Isn't the left side of the expression returning milliseconds while the right side is in seconds. This would explain why the rule is triggered that often.

**Comment by PeteMac88** [comment]
In my opinion this would be the correct expression
```
rate(istio_request_duration_milliseconds_sum{reporter="destination"}[1m]) / rate(istio_request_duration_milliseconds_count{reporter="destination"}[1m]) > 100

```

**Comment by DineshkumarElumalai** [comment]
Hi @PeteMac88 
I'm also facing the same issue. Were you able to identify the root cause?

**Comment by samber** [comment]
Hi @PeteMac88 and sorry for the late reply.

I just fixed the query. Thanks for the report.
