### ISSUE TITLE
Adding alerting rules for solaris exporter

### ISSUE THREAD

**Issue by n27051538** [samber/awesome-prometheus-alerts#244]
Exporter is here https://github.com/n27051538/solaris_exporter
Alert rules are here 
https://github.com/n27051538/solaris_exporter/blob/master/alerts.solaris.yml

**Comment by samber** [comment]
Hi @n27051538 and thanks for the suggestion.

What is the point of this exporter? 🤔

Is it similar to node_exporter?

**Comment by n27051538** [comment]
node_exporter not works on SPARC Solaris, it has no release builds for SPARC platform and it not compiles on go version in Solaris repository.
But I have to monitor this OS, thats why I have to create some solution.
If you not want to create link to my exporter you could provide release build for SPARC Solaris 11 and 10 as alternative :)

**Comment by samber** [comment]
I'm closing this issue since it is a niche exporter.

The yaml file with alerting rules at the root of your repository is good.
