### ISSUE TITLE
cAdvisor docker container queries returning multiple entities.

### ISSUE THREAD

**Issue by darsys** [samber/awesome-prometheus-alerts#254]
Several of the cAdvisor queries return a record for the 'parent' instance.  This record was causing issues with my alerts due to the name label not being set.  For me adding a name filter to the queries resolves the issues.  I am not sure what the result for the parent instance is or if it is useful.  I will create a pr if this seems valid would be useful to others.

I believe this affects the CPU, Memory, Volume IO queries

prometheus:  #v2.30.3
cadvisor: v0.38.8

Example Query showing issue:
`(sum(rate(container_cpu_usage_seconds_total[3m])) BY (instance, name) * 100)`

Typical Result:
{instance="hydra.tayoby.com:8085"} | 191.2053338021866
{instance="hydra.tayoby.com:8085", name="influxdb"} | 0.8246159448528033
**{instance="hydra.tayoby.com:8085"}**
{instance="hydra.tayoby.com:8085", name="prometheus"} | 5.942411989978526
{instance="hydra.tayoby.com:8085", name="nginx-proxy"} | 0.40864163270645487
{instance="hydra.tayoby.com:8085", name="portainer_portainer.1.n1n9oz9hdlkf650umtjiayk9w"} | 0.056343455320733024
{instance="hydra.tayoby.com:8085", name="zabbixagent2"} | 0.8117850332730303
{instance="hydra.tayoby.com:8085", name="ntopng"} | 7.32984562756199
**{instance="themis.tayoby.com:8085"}**
{instance="themis.tayoby.com:8085", name="mosquitto"} | 0.06575496404359865
{instance="themis.tayoby.com:8085", name="cadvisor"} | 2.499325847664766

Example Query showing resolution:
`(sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100)`

Typical Result:
{instance="hydra.tayoby.com:8085", name="influxdb"} | 0.8246159448528033
{instance="hydra.tayoby.com:8085", name="prometheus"} | 5.942411989978526
{instance="hydra.tayoby.com:8085", name="nginx-proxy"} | 0.40864163270645487
{instance="hydra.tayoby.com:8085", name="portainer_portainer.1.n1n9oz9hdlkf650umtjiayk9w"} | 0.056343455320733024
{instance="hydra.tayoby.com:8085", name="zabbixagent2"} | 0.8117850332730303
{instance="hydra.tayoby.com:8085", name="ntopng"} | 7.32984562756199
{instance="themis.tayoby.com:8085", name="mosquitto"} | 0.06575496404359865
{instance="themis.tayoby.com:8085", name="cadvisor"} | 2.499325847664766

See #90 #113 #151

**Comment by samber** [comment]
Thanks for your contribution @darsys ;)
