### ISSUE TITLE
Add a Summary section on the website ?

### ISSUE THREAD

**Issue by tpoindessous** [samber/awesome-prometheus-alerts#257]
Hi ! 

Thanks for your great work !

Could you please, add a Summary section at the top of the main page ? 

something like  :  
 1.1. Prometheus self-monitoring 
 1.2. Host and hardware : node-exporter
etc.

It would be great 😄 

thanks !

**Comment by samber** [comment]
We already have a sidebar for fast navigation.

![image](https://user-images.githubusercontent.com/2951285/144493751-350c3b3e-a39b-49e6-81e3-6f8039ddb224.png)

Can you tell me more about your need?

Would you prefer a list using exporters name? 🤔

**Comment by tpoindessous** [comment]
How are you doing this king of black magic ? 😜 

On Chrome (96.0.4664.55) / MacOS 11.6, I don't have this beautiful sidebar 😭 

When navigating on your website, I first saw the rules page but then, I saw the index page, which has a summary, which is better than nothing.

I will try to "debug" it with DevTools ... 

Thanks ! 


<img width="1016" alt="Capture d’écran 2021-12-02 à 21 46 16" src="https://user-images.githubusercontent.com/3054608/144500320-ccc71c5b-650f-43dc-bb91-9ef831472512.png">

**Comment by samber** [comment]
Ok, your window is too small.

Maybe we could improve this sidebar.

**Comment by tpoindessous** [comment]
Thanks for your answer. I have a special resolution on my macbook pro, to have a bigger font. I changed to default resolution and I saw your sidebar 👍 

But yes, there is a lot of white space on the left side of the screen, which is quite useless 😎

Thanks for your work.

I will close this issue and if you can work on the layout, it will be very cool.

Have a nice day.
