### ISSUE TITLE
PrometheusNotConnectedToAlertmanager not working

### ISSUE THREAD

**Issue by rdiez** [samber/awesome-prometheus-alerts#259]
Alert PrometheusNotConnectedToAlertmanager, which uses metric prometheus_notifications_alertmanagers_discovered, is not working for me.

More information and alternatives are here:

How to detect lost connection to Alertmanager
20.11.2021, 22:17:05
https://groups.google.com/g/prometheus-users/c/vo5PRmu-AA8

**Comment by paulfantom** [comment]
Consider opening this issue in [prometheus/prometheus](https://github.com/prometheus/prometheus) as this is where the alert comes from as seen in https://github.com/prometheus/prometheus/blob/main/documentation/prometheus-mixin/alerts.libsonnet#L63-L78

**Comment by rdiez** [comment]
I opened this issue there:

https://github.com/prometheus/prometheus/issues/9843
