### ISSUE TITLE
Metrics for HPA renamed in 2.x

### ISSUE THREAD

**Issue by debu99** [samber/awesome-prometheus-alerts#266]
The kubernetes_state.hpa.* metrics are not being sent. The reason is that kube-state-metrics 2.x has renamed the metrics internally from kube_hpa_* to kube_horizontalpodautoscaler_* (kubernetes/kube-state-metrics#1003). Same metrics, different prefix.

**Comment by samber** [comment]
Thanks. I made a fix.
