### ISSUE TITLE
"Container Volume IO usage" broken?

### ISSUE THREAD

**Issue by MichaelRoosz** [samber/awesome-prometheus-alerts#276]
```
              - name: Container Volume IO usage
                description: Container Volume IO usage is above 80%
                query: '(sum(container_fs_io_current{name!=""}) BY (instance, name) * 100) > 80'
                severity: warnin
```
What is the idea of this check?
"container_fs_io_current" is documented as "Number of I/Os currently in progress" (see https://github.com/google/cadvisor/blob/master/docs/storage/prometheus.md ). 
Thus I would expect for it to have values like 0,1,2,3 etc. (integer values). But when we multiply 1 by 100 , it is always > 80. So the "> 80 " has absolutely no meaning. And why would we trigger an alert when "container_fs_io_current > 0" which is what we are doing at the moment?

**Comment by samber** [comment]
It must be an error. I just removed the rule.
