### ISSUE TITLE
KubernetesStatefulsetDown alert must be updated with this query

### ISSUE THREAD

**Issue by kocercan** [samber/awesome-prometheus-alerts#277]
KubernetesStatefulsetDown alert is triggering false positive when statefulset replicas set to 0 
It's alerting since I've set a statefulset temproraly to 0 replicas.
I think correct expr must be:
kube_statefulset_replicas != kube_statefulset_status_replicas_ready > 0

the upper expr. only triggering if statefulset pods unready and failing while replicas set more than 0.
![image](https://user-images.githubusercontent.com/65725644/160383797-6b6ac3d8-e998-4ab7-95f4-fe29ac425452.png)
![image](https://user-images.githubusercontent.com/65725644/160384107-8951ffce-2333-4d2e-8231-ed4f99604010.png)

**Comment by samber** [comment]
Fixed
