### ISSUE TITLE
PrometheusAllTargetsMissing alert should be deleted

### ISSUE THREAD

**Issue by ian-kelling** [samber/awesome-prometheus-alerts#283]
It's description claims it is testing for instances being down, but in fact it is only testing for a job in which the up metric doesn't exist, which is impossible according to the prometheus docs, https://prometheus.io/docs/concepts/jobs_instances/ says every job is one or more instance, and every instance gets an up metric. If someone knows that is somehow is possible, it's description and name should be changed to reflect what it is actually testing for.

**Comment by samber** [comment]
Fixed in 3faf133

**Comment by ian-kelling** [comment]
The fix looks good. Thanks!
