### ISSUE TITLE
Percona MongoDB exporter renamed metrics

### ISSUE THREAD

**Issue by laurivosandi** [samber/awesome-prometheus-alerts#290]
Existing metrics seem to be renamed: https://github.com/percona/mongodb_exporter#info-on-percona-mongodb-exporter-versions

**Comment by samber** [comment]
Do you have a list of changes ?

I have no running exporter for mongodb.

**Comment by itspooya** [comment]
I have sent a pull request regarding this issue
https://github.com/samber/awesome-prometheus-alerts/pull/291
