### ISSUE TITLE
PrometheusTimeserieCardinality: undefined variable "$label"

### ISSUE THREAD

**Issue by varac** [samber/awesome-prometheus-alerts#303]
I build all alerts locally to include some of them in my Prometheus setup. I bumped into this error:

```
❯ promtool check rules awesome.prometheus-self-monitoring.alerts.yaml 
Checking awesome.prometheus-self-monitoring.alerts.yaml
  FAILED:
awesome.prometheus-self-monitoring.alerts.yaml: group "awesome_EmbeddedExporter", rule 27, "PrometheusTimeserieCardinality": annotation "description": template: __alert_PrometheusTimeserieCardinality:1: undefined variable "$label"
```

All other alert files that I make use of verify fine with promtool, `PrometheusTimeserieCardinality` seems to be the only rule that doesn't.

Would it be an option to enforce a `promtool check rules` when adding new alerts ? I'm using a [pre-commit](https://pre-commit.com/) check that runs this cmd to check added rules, but I don't know how this could integrate in the workflow here because rules are not added plain but templated.

However, thanks a lot for your effort of maintaining this project, it's awesome indeed !

**Comment by samber** [comment]
I think it has been fixed a few days ago -> https://github.com/samber/awesome-prometheus-alerts/pull/301

Can you confirm it's ok on your side?

**Comment by samber** [comment]
Oops, you're right. It has been fixed in the wrong file. 😁

Thanks for the bug report. I'm going to write the fix.
