### ISSUE TITLE
minio embeded cluster disk offline alert update

### ISSUE THREAD

**Issue by alexandrumarian-portal** [samber/awesome-prometheus-alerts#314]
- name: Minio
        exporters:
          - name: Embedded exporter
            slug: embedded-exporter
            rules:
              - name: Minio disk offline
                description: 'Minio cluster disk is offline'
                query: 'minio_cluster_disk_offline_total > 0'
                severity: critical
              - name: Minio disk space usage
                description: 'Minio available free space is low (< 10%)'
                query: disk_storage_available / disk_storage_total * 100 < 10
                severity: warning
              - name: Minio Node disk offline
                description: 'Minio cluster node disk is offline'
                query: 'minio_cluster_nodes_offline_total > 0'
                severity: critical

**Comment by samber** [comment]
Fixed ;)

Thanks.
