### ISSUE TITLE
elasticsearch_exporter is pointing to old organization (justwatchcom)

### ISSUE THREAD

**Issue by nantiferov** [samber/awesome-prometheus-alerts#316]
Hi,

I noticed that rules for elasticsearch_exporter mention `justwatchcom/elasticsearch_exporter`, while some time ago this exporter migrated to https://github.com/prometheus-community/elasticsearch_exporter

It's definitely more cosmetic issue, but if you don't mind, I can create PR with update.

**Comment by samber** [comment]
yes please!
