### ISSUE TITLE
haproxy (<=v2) rules calculate percentage wrong

### ISSUE THREAD

**Issue by fschlich** [samber/awesome-prometheus-alerts#319]
Many of the `haproxy-exporter-v1` rules try to calculate percentage points instead of going with a fraction, but end up multiplying by 100 the denominator instead of the numerator, such that the alert can never match!

[Example:](https://github.com/samber/awesome-prometheus-alerts/blob/master/_data/rules.yml#L1474)
```
sum by (server) (rate(haproxy_server_http_responses_total{code="5xx"}[1m])) / sum by (server) (rate(haproxy_server_http_responses_total[1m]) * 100) > 5
```
This should correctly read
```
sum by (server) (rate(haproxy_server_http_responses_total{code="5xx"}[1m]) * 100) / sum by (server) (rate(haproxy_server_http_responses_total[1m])) > 5
```
and similarly for other rules

**Comment by samber** [comment]
![](https://media1.giphy.com/media/BxWTWalKTUAdq/giphy.gif?cid=ecf05e47dnej2fewsjdgt39g51x5s5kwoy9s6r7y7rsa9nt5&rid=giphy.gif&ct=g)

Fixed ;)

**Comment by fschlich** [comment]
mind it is not just this one rule that's affected, there are five or so others where the same fix has to be applied (mind though there's one that looks somewhat similar but is different and correct as-is, OTOH the bracket that is multiplied by the `*100` starts at the beginning of the line for that one)

**Comment by samber** [comment]
Oh! you're right
