### ISSUE TITLE
HostHighCpuUsage anomalies

### ISSUE THREAD

**Issue by freak12techno** [samber/awesome-prometheus-alerts#336]
I have a question about the HostHighCpuUsage rule from node_exporter.

As of now, the expression for it is like this:
```
100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100) > 80
```

I've faced the issue when, after rebooting a server, so node_exporter metric would disappear, apparently Prometheus considers the value of the subtracted part as 0, therefore the alert value is 100 and it's triggered.

For my local dashboard I replaces it with the following:

```
sum by ( host) (avg by (mode, host) (rate(node_cpu_seconds_total{mode!="idle"}[2m]))) > 0.8
```
and it seems like it won't trigger alerts once the node is down. Do you think my alert rule would work better or are there any caveats regarding it?

**Comment by samber** [comment]
Good point. I made a fix.
