### ISSUE TITLE
PostgresqlHighRollbackRate wrong query based on the description

### ISSUE THREAD

**Issue by ninkaninus** [samber/awesome-prometheus-alerts#339]
We have been using this query and found that this is a more correct query for this alert and it's description.

Alert: PostgresqlHighRollbackRate
Query:
```(rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres",datid!="0"}[3m])) / ((rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres",datid!="0"}[3m])) + (rate(pg_stat_database_xact_commit{datname!~"template.*|postgres",datid!="0"}[3m]))) > 0.02```

Query with a simpler output:
```sum by (namespace,datname) ((rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres",datid!="0"}[3m])) / ((rate(pg_stat_database_xact_rollback{datname!~"template.*|postgres",datid!="0"}[3m])) + (rate(pg_stat_database_xact_commit{datname!~"template.*|postgres",datid!="0"}[3m])))) > 0.02```

The "datid!=0" is because some postresql instances have a hidden db without a name that can't be removed from the alerts based on the "datname" as "template" and "postgres"

**Comment by samber** [comment]
I see. Thanks for the feedback.

Fixed on master.
