### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by juliusv** [samber/awesome-prometheus-alerts#345]
Currently the domain name (awesome-prometheus-alerts.grep.to) doesn't resolve for me, is this is a known issue?

**Comment by DesireWithin** [comment]
Me too

**Comment by nijave** [comment]
Seems like something is wrong with the registrar `tonic.to`. If you can their whois service, it replies with Cloudflare as the nameserver but querying their nameservers returns `NXDOMAIN`. As a workaround, you can skip tonic.to authoritative DNS by adding these to `/etc/hosts`

```
172.67.178.181 awesome-prometheus-alerts.grep.to
104.21.88.121 awesome-prometheus-alerts.grep.to
```

**Comment by luisdavim** [comment]
disabling the redirect should allow us to use https://samber.github.io/awesome-prometheus-alerts

**Comment by easonboy** [comment]
> It looks like the domain `grep.to` expired. As a workaround, you can skip tonic.to authoritative DNS by adding these to `/etc/hosts`
> 
> ```
> 172.67.178.181 awesome-prometheus-alerts.grep.to
> 104.21.88.121 awesome-prometheus-alerts.grep.to
> ```
> 
> https://www.tonic.to/whois?grep.to
> 
> ```
> Domain:               grep.to
> Created on:           Fri Apr 06 22:43:31 2018
> Last edited on:       Sat Apr 08 02:27:03 2023
> Expires on:           Thu Apr 06 22:43:31 2023
> Primary host add:     173.245.59.67
> Primary host name:    aragorn.ns.cloudflare.com
> Secondary host add:   173.245.58.206
> Secondary host name:  mona.ns.cloudflare.com
> 
> END
> ```
> 
> At some point, the x509 cert will probably expire and fail to renew tho
> 
> The rules are also in the repo: https://github.com/samber/awesome-prometheus-alerts/blob/master/_data/rules.yml

add host to /etc/hosts , and open link response. HTTP ERROR 502

**Comment by juliusv** [comment]
@easonboy Thanks! I want to link to it from another website though, so that's unfortunately not a great general solution. But https://github.com/samber/awesome-prometheus-alerts/issues/345#issuecomment-1503668041 sounds like it would be good.

**Comment by kumalabsconsulting** [comment]
Hi,
It's a shame to lose access to this knowledge base.
I can participate in the purchase of a domain name to help the community.

On the other hand, to host the pages, it would be necessary to see according to the number of visits per day. I could possibly provide a personnal webserver.
Cordially,

**Comment by jimvandervoort** [comment]
Would be really great to have this resource again on GitHub pages. I could also  sponsor a hosting service + analytics (simpleanalytics.com)

**Comment by Cyb3r-Jak3** [comment]
For those who want a mirror, I created one here: https://awesome-prometheus-alerts.cyberjake.xyz/
Will redirect to the live site once it is back.

**Comment by truxnell** [comment]
@Cyb3r-Jak3 Thanks for that, thats been helpful, very not keep to muck around with my hostsfile to get on a mirror!

**Comment by jlosito** [comment]
This looks to be up now on Github pages since the redirect was removed. There's probably some minor fixes need to resolve broken links and whatnot. Would it make sense to close this issue and reopen new issues that address the broken links and whatnot in order to get the site back up in working order?

**Comment by samber** [comment]
Sorry for the delay in the response.

✅  The site is now available under https://samber.github.io/awesome-prometheus-alerts

✅ Last weekend, I successfully ordered back the domain at the new registrar tonic.to.

✅ The redirection from the old domain has been created.

👷‍♂️ The nameservers are propagating.

**Comment by samber** [comment]
DNS NS are propagated and 301 redirections is working ✅

**Comment by juliusv** [comment]
Woot, thanks :)
