### ISSUE TITLE
Display the full alert rule on the website

### ISSUE THREAD

**Issue by obrienrobert** [samber/awesome-prometheus-alerts#356]
A small detail, but on the website (https://samber.github.io/awesome-prometheus-alerts/rules) the example alerts within the code box take up only a small portion of the centre of the page, but we still have to scroll across to see the full alert. I know this might be a limitation of the template used, but it would be nice if the full alert rule was displayed.

**Comment by samber** [comment]
Good point. I made it larger 👌
