### ISSUE TITLE
The alerts for `Container High CPU utilization` is correct?

### ISSUE THREAD

**Issue by LittleWat** [samber/awesome-prometheus-alerts#361]
Hello, thank you for sharing your nice work!

I have a question for the alerts for `Container High CPU utilization`.
https://github.com/samber/awesome-prometheus-alerts/blob/7a05f925b4b2a340f7952534cf7f91da535a72b4/_data/rules.yml#L353

This metrics is not divided by the limit such as `container_spec_cpu_quota` (not like the memory one.)

Could you check if this is really correct, please...?

Thank you!

**Comment by samber** [comment]
I agree, can you fix it, please?

**Comment by skriesch** [comment]
The question is, whether it is a good choice to divide seconds of cpu usage through  a cpu quota. In general, I would look for a cpu max usage in seconds instead of a quota.

**Comment by Matt-Jns** [comment]
From my point of view, this alert should check if the CPU usage is above 80% of the limit given to the container.

My suggestion is:

```
sum(rate(container_cpu_usage_seconds_total{container!=""}[5m])) by (pod, container) /
sum(container_spec_cpu_quota{container!=""}/container_spec_cpu_period{container!=""}) by (pod, container) * 100 > 80
```

**Comment by samber** [comment]
I just made a fix with the query from @Matt-Jns. Thanks for the report.

**Comment by awoisoak** [comment]
I got close to zero experience with it but I think `container_cpu_usage_seconds_total` contains  `name` not `container`?

Besides that, seems like `container_spec_cpu_quota` [might be missing](https://github.com/google/cadvisor/issues/3154) too.
