### ISSUE TITLE
Vault cluster health is incorrect

### ISSUE THREAD

**Issue by sathieu** [samber/awesome-prometheus-alerts#362]
It has: `sum(vault_core_active) / count(vault_core_active) > 0.5`.

It should be: `sum(vault_core_active) / count(vault_core_active) <= 0.5`.

See `vault.core.active` in https://developer.hashicorp.com/vault/docs/internals/telemetry:

> Has a value 1 when the vault node is active, and 0 when node is in standby.

**Comment by samber** [comment]
Thanks for the feedback.

I made a fix
