### ISSUE TITLE
`RedisOutOfConfiguredMaxmemory` for Redis that is solely used for cache?

### ISSUE THREAD

**Issue by fzyzcjy** [samber/awesome-prometheus-alerts#364]
Hi thanks for the alerts! However, when using `RedisOutOfConfiguredMaxmemory` for Redis that is solely used for cache, I wonder whether this is reasonable? IMHO, since that Redis instance is solely used as cache, it is normal for the cache to be full and auto get evict.

**Comment by samber** [comment]
This repository is not intended for being imported straight into a Prometheus instance, without alert selection and threshold adjustment.

You're free to remove some alerts. But even in your case, i'm not even sure it is expected to reach the max memory.

**Comment by fzyzcjy** [comment]
@samber Thank you!

> But even in your case, i'm not even sure it is expected to reach the max memory.

May I know a bit more details? Thanks

**Comment by samber** [comment]
It is usually not a good idea to saturate database resources

I think cache eviction should be done in a different way.

**Comment by fzyzcjy** [comment]
I see. So what method do you suggest to evict the caches?

I know there is TTL (and have set it), but IMHO giving a fixed (range of) TTL may not handle the changeable TPS.
