### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by dudicoco** [samber/awesome-prometheus-alerts#373]
Please add releases so users can get notified of changes to the alerts.
Currently we have to watch all activity in the repo so be notified, which is too verbose.

**Comment by dudicoco** [comment]
@samber you've closed this ads completed but there are still no releases within the project

**Comment by dudicoco** [comment]
@samber now I see that you did create a release, however the releases do not appear in the repository for some reason:
![Screen Shot 2023-08-16 at 9 11 16](https://github.com/samber/awesome-prometheus-alerts/assets/51051860/9c8a93f7-5816-466b-b9b4-6419c984b251)

**Comment by samber** [comment]
Oops, I just forgot to check this :-(

![image](https://github.com/samber/awesome-prometheus-alerts/assets/2951285/e3496b13-22cc-4e99-8343-66b230da9a0a)
