### ISSUE TITLE
KubernetesNodeOutOfPodCapacity fails when multiple replicas of kube-state-metrics

### ISSUE THREAD

**Issue by fcecagno** [samber/awesome-prometheus-alerts#385]
Hi there,

Alert `KubernetesNodeOutOfPodCapacity` gives an error when there are two replicas of `kube-state-metrics` running in the cluster:

```
many-to-many matching not allowed: matching labels must be unique on one side
```

**Comment by jalexander-bb** [comment]
`    expr: sum by (node) ((kube_pod_status_phase{phase="Running"} == 1) + on(uid, instance) group_left(node) (0 * kube_pod_info{pod_template_hash=""})) / sum by (node) (kube_node_status_allocatable{resource="pods"}) * 100 > 90
`
this worked for me, changing it to (uid, instance)
found this is the only unique label i could use

**Comment by samber** [comment]
i just made a commit with your suggested query ;)

closing
