### ISSUE TITLE
Adjust "Kubernetes Volume full in four days" query?

### ISSUE THREAD

**Issue by uhthomas** [samber/awesome-prometheus-alerts#388]
The current query can behave strangely when pods are restarted, as a new time series may be created and consequently missing values will be given to the linear prediction function.

I found that a subquery keeps the linear prediction looking sensible during pod restarts:

```diff
-expr: predict_linear(kubelet_volume_stats_available_bytes[6h], 4 * 24 * 3600) < 0
+expr: predict_linear(kubelet_volume_stats_available_bytes[6h:5m], 4 * 24 * 3600) < 0
```

### Before

<img width="1512" alt="Screenshot 2023-09-18 at 19 04 12" src="https://github.com/samber/awesome-prometheus-alerts/assets/9749173/ae000a28-0429-416d-852e-28eed0d9ca3a">

### After

<img width="1512" alt="Screenshot 2023-09-18 at 19 04 29" src="https://github.com/samber/awesome-prometheus-alerts/assets/9749173/3f9f6790-2ea1-43f2-8777-34a414795f6c">

**Comment by samber** [comment]
Thanks. I made a fix 👌

**Comment by uhthomas** [comment]
Thanks :)
