### ISSUE TITLE
Need to fix use of deprecated apiserver_request_latencies_bucket metric

### ISSUE THREAD

**Issue by muzammil360** [samber/awesome-prometheus-alerts#404]
@samber, it appears that `apiserver_request_latencies_bucket` metric has been deprecated [link](https://github.com/kubernetes/apiserver/issues/59) and the new metric we should be using is `apiserver_request_duration_seconds_bucket`. 

I used the new metric but I am not sure if we should still divide by `1e+06`.

**Comment by samber** [comment]
Fixed 👌 

Thanks for the report.

I removed the `1e+06`
