### ISSUE TITLE
HostFilesystemDeviceError should use `for: 2m`

### ISSUE THREAD

**Issue by baurmatt** [samber/awesome-prometheus-alerts#409]
HostFilesystemDeviceError triggers quite often for me, it seems this is because the metric also tracks "permission denied" events which are resolved on next scrape.

```
Labels:
severity: critical
instance: host.docker.internal:9100
alertname: HostFilesystemDeviceError
device_error: permission denied
job: nodeexporter
device: /dev/mapper/xxxx--yyyy--vg-root
fstype: ext4
```

I'd suggest to increase `for` to `2m`. This seems to resolve those errors for me.

**Comment by samber** [comment]
Thanks for the feedback.

I made a fix 👌
