### ISSUE TITLE
Update Minio metric

### ISSUE THREAD

**Issue by gabrielmusskopf** [samber/awesome-prometheus-alerts#423]
Hi, Minio metric `minio_cluster_disk_offline_total` mentioned at
https://github.com/samber/awesome-prometheus-alerts/blob/8759c50440e0c95363c739432e8c3a21b864c8e0/_data/rules.yml#L2422-L2425
was renamed to `minio_cluster_drive_offline_total`. See https://github.com/minio/minio/commit/c4ca0a5a57e74389d71e82b1a31d74a823d3d51a

**Comment by samber** [comment]
Fixed. Thanks ;)
