### ISSUE TITLE
"Postgresql Invalid Index" alert

### ISSUE THREAD

**Issue by aaii-z** [samber/awesome-prometheus-alerts#429]
Hi,

I wanted to use the "Postgresql Invalid Index" alert, but it requires the metric pg_general_index_info_pg_relation_size, which I couldn't find in the postgres_exporter. Is this a custom query? If so, could you provide guidance on how to implement it?

I would appreciate any assistance you can offer.

Thank you for your help.

**Comment by samber** [comment]
Thanks for the report.

First, there is a type: `genaral` -> `general`, then a comment is missing.

I made a fix 👌 

![image](https://github.com/user-attachments/assets/953e0ce4-9d53-4da9-9ec8-2cd9ca15dd78)
