### ISSUE TITLE
[hwmon] Rule for alert about critical temperature.

### ISSUE THREAD

**Issue by izmal** [samber/awesome-prometheus-alerts#433]
Hello!

The alarm metrics depend on the path to the alarm for sensors. This behavior might be related to a feature or potential bug in how node_exporter scans `/sys/class/hwmon` - see https://github.com/prometheus/node_exporter/blob/master/collector/hwmon_linux.go#L284. The metric names are built via concatenation of the file name components.

For example:
- For NVMe: `/sys/class/hwmon/hwmon0/temp1_alarm` results in the metric `node_hwmon_temp_alarm`
- For CPU: `/sys/class/hwmon/hwmon1/temp10_crit_alarm` results in the metric `node_hwmon_temp_crit_alarm_celsius`
```
node_hwmon_temp_alarm{chip="nvme_nvme0",sensor="temp1"} 0
node_hwmon_temp_crit_alarm_celsius{chip="platform_coretemp_1",sensor="temp10"} 0
```

To create a comprehensive alert that covers both cases, we can use:

```promql
(node_hwmon_temp_crit_alarm_celsius == 1) or (node_hwmon_temp_alarm == 1)
```
cc: @samber

_Originally posted by @izmal in https://github.com/samber/awesome-prometheus-alerts/issues/200#issuecomment-2313723783_

**Comment by samber** [comment]
Fixed in 995ab4d27a5cdaa8045f1103f15a7161c4b245b3 ✌️
