### ISSUE TITLE
Netdata metrics name is wrong

### ISSUE THREAD

**Issue by jiangxiaobai** [samber/awesome-prometheus-alerts#443]
Netdata's metrics have the wrong name, for example netdata_system_ram_MB_average, the correct one is netdata_system_ram_MiB_average.My netdata version is 1.46.And after I changed the name of the metric correctly, I used the expression 100 / netdata_system_ram_MiB_average * netdata_system_ram_MiB_average{dimension=~“free|cached”} in the document to calculate the memory usage, and the result was basically 100, which does not match the actual。

**Comment by samber** [comment]
Fixed!
