### ISSUE TITLE
Docker Containers Alert Rules

### ISSUE THREAD

**Issue by mark-veenstra** [samber/awesome-prometheus-alerts#46]
Hi,
Thanks for this great overview!
I am testing the rules and I have a question about it.

I just implemented these rules: https://awesome-prometheus-alerts.grep.to/rules#docker-containers. They are firing, but I am not sure if the query is correct.

The following queries:
* 3.2. Container CPU usage
* 3.3. Container Memory usage
* 3.4. Container Volume usage
* 3.5. Container Volume IO usage

Are all using a sum by ip. But those metrics do not have any ip added on it.

I am running following versions:
* cAdvisor v0.32.0
* prometheus v2.11.1
* alertmanager v0.18.0

Are there some requirements to get the ip? Or should it be changed to `instance`?

**Comment by samber** [comment]
fixed by https://github.com/samber/awesome-prometheus-alerts/pull/72
