### ISSUE TITLE
 7.7. Dead locks

### ISSUE THREAD

**Issue by obeyler** [samber/awesome-prometheus-alerts#52]
pg_stat_database_deadlocks{pg_stat_database_de}[1m]
is an invalid expression 

 7.7. Dead locks
PostgreSQL has dead-locks

- alert: DeadLocks
  expr: rate(pg_stat_database_deadlocks{pg_stat_database_de}[1m]) > 0
  for: 5m
  labels:
    severity: warning
  annotations:
    summary: "Dead locks (instance {{ $labels.instance }})"
    description: "PostgreSQL has dead-locks\n  VALUE = {{ $value }}\n  LABELS: {{ $labels

**Comment by samber** [comment]
fixed by https://github.com/samber/awesome-prometheus-alerts/pull/53
