### ISSUE TITLE
discussion about blackbox probe_http_duration_seconds alert

### ISSUE THREAD

**Issue by GETandSELECT** [samber/awesome-prometheus-alerts#57]
Hey

https://github.com/samber/awesome-prometheus-alerts/blob/3040fe56d5943bbfd75e5c7adc8bfc4172a011f5/_data/rules.yml#L533-L536

I recommend replace with something like this:

`avg_over_time(probe_duration_seconds{env="Prod"}[15m]) > 1`

what others think? Should I do a PR?

**Comment by samber** [comment]
Hi @GETandSELECT 

15min is way to long for this kind of issues.
But I think you're right, avg over a short time looks nicer here.

I will also decrease threshold to 1s.

**Comment by samber** [comment]
Done in https://github.com/samber/awesome-prometheus-alerts/commit/4f9e88bad492d882285d12ef688fc1d2448f0172
