### ISSUE TITLE
There's no easy way to copy-paste the rules

### ISSUE THREAD

**Issue by toresbe** [samber/awesome-prometheus-alerts#59]
One thing that was slightly frustrating when copying these rules over to my deployment was the fact that if you just want to chuck all the alerts into the relevant YAML file you have to copy-paste each one individually.

Some sort of presentation that would allow you to get a relevant exporter's rules in one solid chunk for ease of copypasta would be very welcome.

**Comment by samber** [comment]
Definitely !

We need a "Copy all" button !

**Comment by samber** [comment]
Done in #61

Thanks for the proposal ;)

**Comment by toresbe** [comment]
You're the best! Thanks!
