### ISSUE TITLE
How to filter out master in ReplicationLag

### ISSUE THREAD

**Issue by Behoston** [samber/awesome-prometheus-alerts#74]
I have data from postgres-exporter: https://github.com/socialwifi/docker-postgres-exporter/blob/master/queries.yaml#L1
But it also returns very big value for master node. Idk how to filter it out on alertmanager level.

```
604800 > pg_replication_lag > 10
```
Looks very stupid, but works fine. Assuming alerts should fire and fixed in one week. 

However, master node can change in any time, so replication lag will be lower for master during change, so I keep looking for better solution.

**Comment by samber** [comment]
Can you list labels of this metrics please ?

**Comment by Behoston** [comment]
```
pg_replication_lag{endpoint="metrics",instance="x.x.x.a:xxxx",job="postgres-exporter",namespace="xxx",server="localhost:xxxx",service="postgres-exporter-x-x-x-a"}
```
Only difference is IP, all other labes are same

**Comment by samber** [comment]
What is the result of `SELECT pg_is_in_recovery();` on newly promoted master node ?

How do you manage master node failover ?

Looks like your new primary node is still considered as a slave.

**Comment by samber** [comment]
`pg_replication_lag` value is:
- NaN on standalone instances
- the expected replication lag on standby servers
- a forever increasing value for promoted master nodes

I suggest you add a label in query, excluding master nodes ;)

https://github.com/samber/awesome-prometheus-alerts/pull/84

Closing this issue. Please re-open if necessary ;)
Thanks for the report anyway.
