### ISSUE TITLE
node-exporter nfs alerts

### ISSUE THREAD

**Issue by Tsukiand** [samber/awesome-prometheus-alerts#81]
I collect the nfs stats using node-exporter and i want to monitoring the nfs stats. But i have have no idea how to set the threshold, for example nfs request latency. Can someone give me advice about the threshold of nfs stats.

**Comment by samber** [comment]
Hi @Tsukiand 

I don't have any NFS setup on my servers.

Could you please copy-paste here an example of x.x.x.x:9100/metrics response you get ?
