### ISSUE TITLE
ContainerCpuUsage reports kubernetes-cadvisor metrics

### ISSUE THREAD

**Issue by mizhkeao** [samber/awesome-prometheus-alerts#90]
kubernetes-cadvisor is a process that runs in the kubelet. Consider changing the query for ContainerCpuUsage from 

(sum(rate(container_cpu_usage_seconds_total[3m])) BY (instance, name) * 100) > 80

to 

(sum(rate(container_cpu_usage_seconds_total{job!="kubernetes-cadvisor"}[3m])) BY (instance, name) * 100) > 80

so that the alert won't fire constantly for cadvisor?

<img width="1438" alt="截屏2020-03-15 下午1 02 33" src="https://user-images.githubusercontent.com/55338389/76695685-3eff6b00-66bd-11ea-9bba-3bb8a2a501ad.png">

**Comment by samber** [comment]
Why does your cAdvisor instance is consuming so many CPUs ?!

If you need to exclude cAdvisor, you should filter by image, not job.

**Comment by CodyGuo** [comment]
```shell
(sum(rate(container_cpu_usage_seconds_total{name!=""}[3m])) BY (instance, name) * 100)
```

**Comment by samber** [comment]
Closing.

I consider cAdvisor should not burn your CPU.
Hiding the alert won't solve any performance issue...

Feel free to reopen it in case you think I'm wrong ;)
